# Generated by Django 4.2.11 on 2024-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
