# Generated by Django 4.2.11 on 2024-04-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selectionprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
