# Generated by Django 5.0.3 on 2024-04-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
