# Generated by Django 5.0.3 on 2024-04-13 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0002_alter_customuser_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='postulation',
            field=models.ManyToManyField(blank=True, null=True, related_name='postulation', to='GRH.vacancy'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, through='GRH.Team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
