# Generated by Django 4.2.11 on 2024-04-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
