# Generated by Django 5.0.3 on 2024-04-14 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='postulation',
            field=models.ManyToManyField(blank=True, related_name='postulation', to='GRH.vacancy'),
        ),
        migrations.AlterField(
            model_name='role',
            name='team_members',
            field=models.ManyToManyField(blank=True, through='GRH.Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
