# Generated by Django 4.2.11 on 2024-04-18 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0005_alter_role_job_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, through='GRH.Team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='contest_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRH.selectionprocess'),
        ),
        migrations.AlterField(
            model_name='team',
            name='postulant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRH.role'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='selection_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRH.selectionprocess'),
        ),
    ]
