# Generated by Django 4.2.11 on 2024-04-18 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0006_alter_role_team_members_alter_stage_contest_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='team_members',
            field=models.ManyToManyField(blank=True, through='GRH.Team', to=settings.AUTH_USER_MODEL),
        ),
    ]
