# Generated by Django 4.2.11 on 2024-04-23 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRH', '0008_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='GRH.vacancy'),
        ),
        migrations.AlterField(
            model_name='role',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='positions', through='GRH.Team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='contest_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='GRH.selectionprocess'),
        ),
    ]
