# Generated by Django 5.0.3 on 2024-04-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRING', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_stage',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_stages', to='HIRING.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate_stage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_candidates', to='HIRING.stage'),
        ),
    ]
